version: "3.9"

services:

  database:
    container_name: buckythebadgerbot-db
    image: postgres:15.1
    restart: on-failure
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    expose:
      - "5432"
    volumes:
      - ./data/database/db_init.sql:/docker-entrypoint-initdb.d/db_init.sql
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 10s
      retries: 5
    networks:
      - buckythebadgerbot

  discord-bot:
    container_name: buckythebadgerbot-app
    image: ghcr.io/rittvic/buckythebadgerbot:latest
    restart: on-failure
    depends_on:
      database:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - ./data/grade-dist-graphs:/app/grade-dist-graphs
    networks:
      - buckythebadgerbot

volumes:
  postgres-data:

networks:
  buckythebadgerbot:
    name: buckythebadgerbot
